/**
 * Utility to generate report formats: HTML, Markdown, and JSON
 */

const generateMarkdownReport = (analysis) => {
  let md = `# AI Bug Detector - Code Analysis Report\n\n`;
  md += `**Project Name:** ${analysis.projectName}\n`;
  md += `**Language:** ${analysis.language}\n`;
  md += `**Date:** ${new Date(analysis.createdAt).toLocaleString()}\n`;
  md += `**Quality Score:** ${analysis.metrics.overallQualityScore}/100\n`;
  md += `**Confidence Score:** ${analysis.confidenceScore}%\n\n`;

  md += `## 1. Summary\n${analysis.summary}\n\n`;

  md += `## 2. Code Metrics\n`;
  md += `- **Complexity:** ${analysis.metrics.complexity}\n`;
  md += `- **Readability Score:** ${analysis.metrics.readabilityScore}/100\n`;
  md += `- **Maintainability Score:** ${analysis.metrics.maintainabilityScore}/100\n`;
  md += `- **Estimated Execution Time:** ${analysis.metrics.estimatedExecutionTime}\n`;
  md += `- **Estimated Memory Usage:** ${analysis.metrics.estimatedMemoryUsage}\n\n`;

  md += `## 3. Detected Issues\n`;
  if (analysis.bugs.length === 0) {
    md += `No critical bugs detected!\n`;
  } else {
    analysis.bugs.forEach((bug, index) => {
      md += `### [${bug.severity}] Issue ${index + 1}: ${bug.category}\n`;
      if (bug.line) md += `- **Line Number:** ${bug.line}\n`;
      md += `- **Problem:** ${bug.message}\n`;
      md += `- **Explanation:** ${bug.explanation}\n\n`;
    });
  }

  md += `## 4. Optimization Suggestions\n`;
  analysis.optimizationSuggestions.forEach((suggestion) => {
    md += `- ${suggestion}\n`;
  });
  md += `\n`;

  md += `## 5. Line-by-Line Refactoring Explanations\n`;
  if (analysis.lineExplanations.length === 0) {
    md += `No line modifications required.\n`;
  } else {
    analysis.lineExplanations.forEach((exp) => {
      md += `- **Line ${exp.line}:**\n`;
      md += `  - *Original:* \`${exp.originalLine.trim()}\`\n`;
      md += `  - *Fixed:* \`${exp.fixedLine.trim()}\`\n`;
      md += `  - *Why:* ${exp.explanation}\n`;
    });
  }

  md += `\n---\nReport generated by AI Bug Detector.`;
  return md;
};

const generateHTMLReport = (analysis) => {
  const bugRows = analysis.bugs.map((bug, index) => `
    <div class="card severity-${bug.severity.toLowerCase()}">
      <h3>[${bug.severity}] ${bug.category} ${bug.line ? `(Line ${bug.line})` : ''}</h3>
      <p><strong>Problem:</strong> ${bug.message}</p>
      <p><strong>Details:</strong> ${bug.explanation}</p>
    </div>
  `).join('');

  const suggestionsList = analysis.optimizationSuggestions.map(s => `<li>${s}</li>`).join('');

  const explanationRows = analysis.lineExplanations.map(exp => `
    <tr>
      <td>${exp.line}</td>
      <td class="code-line delete">${escapeHtml(exp.originalLine)}</td>
      <td class="code-line add">${escapeHtml(exp.fixedLine)}</td>
      <td>${exp.explanation}</td>
    </tr>
  `).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title>AI Bug Detector Report - ${analysis.projectName}</title>
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        color: #1f2937;
        background-color: #f9fafb;
        padding: 40px;
        line-height: 1.6;
        max-width: 900px;
        margin: 0 auto;
      }
      .header {
        border-bottom: 2px solid #e5e7eb;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }
      .header h1 { margin: 0 0 10px 0; color: #111827; }
      .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
      .meta-box { background: #fff; padding: 15px; border-radius: 8px; border: 1px solid #e5e7eb; }
      .metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-bottom: 30px; }
      .metric-box { background: #eff6ff; padding: 15px; border-radius: 8px; text-align: center; border: 1px solid #bfdbfe; }
      .metric-box h4 { margin: 0; color: #1e40af; font-size: 14px; text-transform: uppercase; }
      .metric-box p { margin: 5px 0 0 0; font-size: 24px; font-weight: bold; color: #1d4ed8; }
      .card { background: white; padding: 20px; border-radius: 8px; border-left: 5px solid #ccc; margin-bottom: 15px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
      .severity-critical { border-left-color: #dc2626; background-color: #fef2f2; }
      .severity-high { border-left-color: #f97316; background-color: #fff7ed; }
      .severity-medium { border-left-color: #eab308; background-color: #fef9c3; }
      .severity-low { border-left-color: #3b82f6; background-color: #eff6ff; }
      .severity-informational { border-left-color: #10b981; background-color: #ecfdf5; }
      table { width: 100%; border-collapse: collapse; margin-top: 20px; background: white; }
      th, td { padding: 12px; border: 1px solid #e5e7eb; text-align: left; font-size: 14px; }
      th { background-color: #f3f4f6; }
      .code-line { font-family: monospace; font-size: 12px; white-space: pre-wrap; }
      .code-line.delete { background-color: #fee2e2; text-decoration: line-through; }
      .code-line.add { background-color: #dcfce7; }
      ul { padding-left: 20px; }
      li { margin-bottom: 8px; }
    </style>
  </head>
  <body>
    <div class="header">
      <h1>AI Bug Detector Report</h1>
      <p>Comprehensive code analysis audit results</p>
    </div>

    <div class="meta">
      <div class="meta-box">
        <p><strong>Project Name:</strong> ${analysis.projectName}</p>
        <p><strong>Language:</strong> ${analysis.language}</p>
        <p><strong>Date:</strong> ${new Date(analysis.createdAt).toLocaleString()}</p>
      </div>
      <div class="meta-box">
        <p><strong>Confidence Score:</strong> ${analysis.confidenceScore}%</p>
        <p><strong>Estimated Execution Time:</strong> ${analysis.metrics.estimatedExecutionTime}</p>
        <p><strong>Estimated Memory Usage:</strong> ${analysis.metrics.estimatedMemoryUsage}</p>
      </div>
    </div>

    <div class="metrics">
      <div class="metric-box">
        <h4>Quality Score</h4>
        <p>${analysis.metrics.overallQualityScore}/100</p>
      </div>
      <div class="metric-box">
        <h4>Readability</h4>
        <p>${analysis.metrics.readabilityScore}/100</p>
      </div>
      <div class="metric-box">
        <h4>Maintainability</h4>
        <p>${analysis.metrics.maintainabilityScore}/100</p>
      </div>
    </div>

    <h2>Executive Summary</h2>
    <p>${analysis.summary}</p>

    <h2>Detected Code Anomalies</h2>
    <div class="bugs-list">
      ${bugRows || '<p>No anomalies detected. Code is clear.</p>'}
    </div>

    <h2>Optimization Suggestions</h2>
    <ul>
      ${suggestionsList}
    </ul>

    <h2>Refactoring Explanations</h2>
    <table>
      <thead>
        <tr>
          <th style="width: 8%">Line</th>
          <th style="width: 32%">Original</th>
          <th style="width: 32%">Fixed</th>
          <th style="width: 28%">Explanation</th>
        </tr>
      </thead>
      <tbody>
        ${explanationRows || '<tr><td colspan="4" style="text-align:center">No line adjustments required.</td></tr>'}
      </tbody>
    </table>

    <footer style="margin-top: 50px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 20px;">
      Report generated securely by AI Bug Detector.
    </footer>
  </body>
  </html>
  `;
};

function escapeHtml(text) {
  if (!text) return '';
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

module.exports = {
  generateMarkdownReport,
  generateHTMLReport
};
